import './globals.css';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: JSX.Element }): JSX.Element {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
